### ISSUE TITLE
Build fail after merging new page

### ISSUE THREAD

**Issue by aceade** [aceade/sydfjords#18]
After merging #4, which had new images, the build is failing to push the new content:

> [vite]: Rollup failed to resolve import "/sydfjords/whales/whale-480w.webp" from "/home/runner/work/sydfjords/sydfjords/src/components/WhaleWatching.vue".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
> ✓ 30 modules transformed.
> ✓ built in 650ms
> error during build:
> Error: [vite]: Rollup failed to resolve import "/sydfjords/whales/whale-480w.webp" from "/home/runner/work/sydfjords/sydfjords/src/components/WhaleWatching.vue".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
>     at viteWarn (file:///home/runner/work/sydfjords/sydfjords/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:48069:27)
>     at onRollupWarning (file:///home/runner/work/sydfjords/sydfjords/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:48101:9)
>     at onwarn (file:///home/runner/work/sydfjords/sydfjords/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:47829:13)
>     at file:///home/runner/work/sydfjords/sydfjords/node_modules/.pnpm/rollup@3.28.0/node_modules/rollup/dist/es/shared/node-entry.js:24152:13
>     at Object.logger [as onLog] (file:///home/runner/work/sydfjords/sydfjords/node_modules/.pnpm/rollup@3.28.0/node_modules/rollup/dist/es/shared/node-entry.js:25825:9)
>     at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/sydfjords/sydfjords/node_modules/.pnpm/rollup@3.28.0/node_modules/rollup/dist/es/shared/node-entry.js:24738:26)
>     at file:///home/runner/work/sydfjords/sydfjords/node_modules/.pnpm/rollup@3.28.0/node_modules/rollup/dist/es/shared/node-entry.js:24698:26

**Comment by aceade** [comment]
Digging through the docs suggest I need to include the [assetsInclude](https://vitejs.dev/config/shared-options.html#assetsinclude) option.

**Comment by aceade** [comment]
Transforming asset URLs so they don't include an absolute path fixes _part_ of it, but now icons and the "hero" images from the home page and Colwdvatn don't work.
